import type { ResourceCandidate } from "../research/source-types.js";

export const DOC_REGISTRY: ResourceCandidate[] = [
  {
    title: "Meta Marketing API",
    product: "Meta Marketing API",
    domain: "ads",
    url: "https://developers.facebook.com/docs/marketing-api/",
    tier: "official_docs",
    topics: ["ads", "api", "campaigns", "insights", "audiences"],
    keywords: ["meta", "facebook", "marketing api", "graph api", "ads api"],
    reason: "Official Meta Marketing API documentation.",
    source: "registry",
  },
  {
    title: "Google Ads API",
    product: "Google Ads API",
    domain: "ads",
    url: "https://developers.google.com/google-ads/api/docs/start",
    tier: "official_docs",
    topics: ["ads", "api", "campaigns", "reporting"],
    keywords: ["google ads", "google ads api", "google advertising"],
    reason: "Official Google Ads API documentation.",
    source: "registry",
  },
  {
    title: "TikTok API for Business",
    product: "TikTok API for Business",
    domain: "ads",
    url: "https://business-api.tiktok.com/portal/docs",
    tier: "official_docs",
    topics: ["ads", "api", "campaigns", "reporting"],
    keywords: ["tiktok", "tiktok ads", "tiktok business api"],
    reason: "Official TikTok API for Business documentation.",
    source: "registry",
  },

  {
    title: "OpenAI API Docs",
    product: "OpenAI API",
    domain: "ai",
    url: "https://platform.openai.com/docs",
    tier: "official_docs",
    topics: ["ai", "llm", "api", "models"],
    keywords: ["openai", "gpt", "openai api", "chatgpt api"],
    reason: "Official OpenAI API documentation.",
    source: "registry",
  },
  {
    title: "Anthropic API Docs",
    product: "Anthropic Claude API",
    domain: "ai",
    url: "https://docs.anthropic.com/",
    tier: "official_docs",
    topics: ["ai", "llm", "api", "claude"],
    keywords: ["anthropic", "claude", "claude api"],
    reason: "Official Anthropic documentation.",
    source: "registry",
  },
  {
    title: "NVIDIA AI Endpoints",
    product: "NVIDIA AI Endpoints",
    domain: "ai",
    url: "https://docs.api.nvidia.com/",
    tier: "official_docs",
    topics: ["ai", "llm", "embedding", "api"],
    keywords: ["nvidia", "nvidia ai", "nvidia api", "nvidia embeddings"],
    reason: "Official NVIDIA AI API documentation.",
    source: "registry",
  },

  {
    title: "Qdrant Documentation",
    product: "Qdrant",
    domain: "database",
    url: "https://qdrant.tech/documentation/",
    tier: "official_docs",
    topics: ["vector database", "retrieval", "search", "embeddings"],
    keywords: ["qdrant", "vector db", "vector database", "semantic search"],
    reason: "Official Qdrant documentation.",
    source: "registry",
  },
  {
    title: "Supabase Documentation",
    product: "Supabase",
    domain: "database",
    url: "https://supabase.com/docs",
    tier: "official_docs",
    topics: ["postgres", "database", "auth", "storage"],
    keywords: ["supabase", "postgres", "supabase auth", "supabase database"],
    reason: "Official Supabase documentation.",
    source: "registry",
  },
  {
    title: "Prisma Documentation",
    product: "Prisma",
    domain: "database",
    url: "https://www.prisma.io/docs",
    tier: "official_docs",
    topics: ["orm", "database", "postgres"],
    keywords: ["prisma", "orm", "prisma client", "prisma migrate"],
    reason: "Official Prisma documentation.",
    source: "registry",
  },

  {
    title: "Next.js Documentation",
    product: "Next.js",
    domain: "web",
    url: "https://nextjs.org/docs",
    tier: "official_docs",
    topics: ["nextjs", "react", "frontend", "app router"],
    keywords: ["nextjs", "next.js", "react app router"],
    reason: "Official Next.js documentation.",
    source: "registry",
  },
  {
    title: "TanStack Query Documentation",
    product: "TanStack Query",
    domain: "web",
    url: "https://tanstack.com/query/latest/docs/framework/react/overview",
    tier: "official_docs",
    topics: ["react", "query", "cache", "polling"],
    keywords: ["tanstack query", "react query", "polling", "cache"],
    reason: "Official TanStack Query documentation.",
    source: "registry",
  },
  {
    title: "Fastify Documentation",
    product: "Fastify",
    domain: "backend",
    url: "https://fastify.dev/docs/latest/",
    tier: "official_docs",
    topics: ["backend", "node", "api", "server"],
    keywords: ["fastify", "node api", "fastify server"],
    reason: "Official Fastify documentation.",
    source: "registry",
  },

  {
    title: "Scrapling GitHub",
    product: "Scrapling",
    domain: "scraping",
    url: "https://github.com/D4Vinci/Scrapling",
    tier: "official_docs",
    topics: ["scraping", "crawler", "html extraction"],
    keywords: ["scrapling", "scraper", "web scraping", "fetcher"],
    reason: "Official Scrapling repository.",
    source: "registry",
  },
  {
    title: "Microsoft MarkItDown",
    product: "MarkItDown",
    domain: "document-processing",
    url: "https://github.com/microsoft/markitdown",
    tier: "official_docs",
    topics: ["document conversion", "markdown", "pdf", "docx"],
    keywords: ["markitdown", "pdf to markdown", "docx to markdown"],
    reason: "Official MarkItDown repository.",
    source: "registry",
  },
];
